spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mhsite_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mhksite
    password: aptx4896

  jpa:
    hibernate:
      # create : app가동 후 SessionFactory가 실행될 때 기존 테이블을 지우고 새로 생성.
      # create-drop : create와 동일 but app을 종료하면 테이블을 삭제한다.
      # update: SessionFactory가 실행될 때, 객체를 검사하여 변경된 스키마를 갱신. 기존 데이터는 유지
      # validate : update처럼 객체를 검사하지만 스키마는 건드리지 않는다. DB의 테이블 정보와 객체 정보다 다르면 에러를 발생.
      # none: ddl-auto 기능을 사용하지 않는다.
      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      # 로그에 하이버네이트가 생성한 쿼리문을 출력하는 옵션 format_sql을 통해 보기좋게 포매팅 가능.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: debug